"""
Copyright (C) 2019 rerobots, Inc.
"""

import os.path
import subprocess

from setuptools import setup


def get_githash():
    """Try to get commit hash for this code."""
    try:
        hashstr = subprocess.check_output(
            ['git', 'log', '-1', '--pretty=%H'], text=True
        )
        hashstr = hashstr.strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None
    return hashstr


with open(os.path.join('..', 'VERSION'), 'rt') as fp:
    VERSION = fp.read()
if not os.path.exists(os.path.join('..', 'RELEASE')):
    VERSION += '.dev0'
    HASHSTR = get_githash()
    if HASHSTR:
        VERSION += f'+{HASHSTR}'
with open('rerobots_apiw/_version.py', 'w') as fp:
    fp.write(
        f'''"""This file was automatically generated by setup.py. Do not edit.
"""
__version__ = '{VERSION}'
'''
    )


setup(
    version=VERSION,
    author_email='scott@rerobots',
    packages=[
        'rerobots_apiw',
        'rerobots_apiw.addons',
        'rerobots_shared',
    ],
    install_requires=[
        # Defined in Pipfile
    ],
)
