"""
Copyright (C) 2019 rerobots, Inc.
"""

import os.path
import subprocess

from setuptools import setup


def get_githash():
    """Try to get commit hash for this code."""
    try:
        hashstr = subprocess.check_output(
            ['git', 'log', '-1', '--pretty=%H'], universal_newlines=True
        )
        hashstr = hashstr.strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None
    return hashstr


with open(os.path.join('..', 'VERSION'), 'rt') as fp:
    VERSION = fp.read()
if not os.path.exists(os.path.join('..', 'RELEASE')):
    VERSION += '.dev0'
    HASHSTR = get_githash()
    if HASHSTR:
        VERSION += '+{}'.format(HASHSTR)
with open('rerobots_apiw/_version.py', 'w') as fp:
    fp.write(
        '''"""This file was automatically generated by setup.py. Do not edit.
"""
__version__ = '{}'
'''.format(VERSION)
    )


setup(
    name='rerobots_apiw',
    version=VERSION,
    author_email='scott@rerobots',
    packages=[
        'rerobots_apiw',
        'rerobots_apiw.addons',
        'rerobots_infra',
    ],
    install_requires=[
        'aiocache[redis]>=0.11,<0.12',
        'aiocontextvars',
        'aiohttp>=3.8,<3.9',
        'aioredis<2',  # version 2 in production throws exception: AttributeError: module 'aioredis' has no attribute 'create_pool'
        'celery',
        'cryptography',
        'geoip2',
        'gunicorn>=20.1,<20.2',
        'pika==1.2',
        'psycopg2',
        'pyjwt<2',
        'redis',
        'requests>=2.32,<2.33',
        'sentry-sdk>=1.5,<1.6',
        'sqlalchemy>=1.3,<2.0',
    ],
)
