services:
  redis:
    image: rerobots/ext/redis
    ports:
      - "127.0.0.1:6379:6379"

  postgres:
    image: rerobots/ext/postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - psql:/var/lib/postgresql/14/main

  rabbitmq:
    image: rerobots/ext/rabbitmq
    ports:
      - "127.0.0.1:5672:5672"

volumes:
  psql: