"""
Copyright (C) 2019 rerobots, Inc.
"""

import os.path
import subprocess

from setuptools import setup


def get_githash():
    """Try to get commit hash for this code."""
    try:
        hashstr = subprocess.check_output(
            ['git', 'log', '-1', '--pretty=%H'], universal_newlines=True
        )
        hashstr = hashstr.strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None
    return hashstr


with open(os.path.join('..', 'VERSION'), 'rt') as fp:
    VERSION = fp.read()
if not os.path.exists(os.path.join('..', 'RELEASE')):
    VERSION += '.dev0'
    HASHSTR = get_githash()
    if HASHSTR:
        VERSION += '+{}'.format(HASHSTR)
with open('rerobots_infra/_version.py', 'w') as fp:
    fp.write(
        '''"""This file was automatically generated by setup.py. Do not edit.
"""
__version__ = '{}'
'''.format(VERSION)
    )


setup(
    name='rerobots_infra',
    version=VERSION,
    author_email='scott@rerobots',
    packages=['rerobots_infra'],
    install_requires=[
        'pika==1.2',
    ],
)
